name:                wikipedia-map
version:             0.1.0.0
github:              "vaibhavnaagar/wikipedia-map"
license:             MIT
author:              "Vaibhav Nagar"
maintainer:          "vaibhavn@iitk.ac.in"
copyright:           "2018 Vaibhav Nagar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Visualize connections based on links between wikipedia pages
category:            API and Web-App

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/vaibhavnaagar/wikipedia-map#readme>

dependencies:
- base >= 4.7 && < 5
- network-uri
- HTTP
- http-client
- http-client-tls
- http-types
- bytestring
- text
- aeson
- conduit
- conduit-extra
- http-conduit
- unordered-containers
- html-parse
- servant
- servant-server
- wai
- warp
- transformers

library:
  source-dirs: src

executables:
  wikipedia-map-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wikipedia-map

tests:
  wikipedia-map-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wikipedia-map
